import Navbar from "../Navbar/Navbar"
import Head from "next/head";

interface LayoutProps {
  children: React.ReactNode;
}

const Layout: React.FC<LayoutProps> = ({ children }) =>{
  return (
    <>
          <Head>
        <title>Darren Medrano</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon"/>
      </Head>
      <Navbar />
      <main>{children}</main>
    </>
  );
}

export default Layout;