import Head from "next/head";
import { useState } from "react"
import { VStack, AbsoluteCenter, Box, Heading, Button } from "@chakra-ui/react"
import MyButton from "../components/MyButton";
import Links from "../components/Links/Links"




const Home = () => {
  const [isVisible, setIsVisible] = useState(true);

  const onClick = (e) => {
    setIsVisible((prev) => !prev);
  };

  return (
    <>
      <Head>
        <title>Darren Medrano</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"></meta>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" />
      </Head>
      <Box h={{
        base: "800",
        sm: "950"
      }}
backgroundColor="black"
       >
        <AbsoluteCenter axis="both">
          <VStack spacing={{
            base: 4,
            md: 10
          }}>
          
          <Heading className="typed-heading2" as="h1" size={{
              base: "4xl",
              md: "4xl"
            }}
            bgGradient='linear(to-l, #7928CA, #FF0080)' 
            bgClip='text' p={4}>Let&#x27;s Build Something</Heading>
 <Button onClick={onClick} style={{
  backgroundColor: "transparent", color:"white", animation: "glow 2s ease-in-out infinite"}} size={{
    base:"sm",
    md:"lg"}} mb={10} transisition="all 0.3s ease" _hover={{  transform: "translate3d(0, -10px, 22px)" }}>Learn More</Button>
            {isVisible ? "" : (<Links/>)}      
          </VStack>
        </AbsoluteCenter>
        
      </Box>
    </>
  )
}

export default Home;
