import Head from "next/head";
import { useState, useEffect } from "react";
import { Avatar} from "@chakra-ui/react";
import ActiveRepos from "../components/activeRepos/ActiveRepos";
import styles from "../styles/profile.module.css"
import ContributionCalendar from "../components/contributionCalendar/ContributionCalendar";

export default function Home() {

  const [bio, setBio] = useState("");
  const [username, setUsername] = useState("");
  const [avatarUrl, setAvatarUrl] = useState("");


  useEffect(() => {
    async function fetchGitHubData() {
      const url = "https://api.github.com/users/medranomiler"
      const response = await fetch(url);
      const data = await response.json();
      setUsername(data.login);
      setBio(data.bio);
      setAvatarUrl(data.avatar_url);
      console.log(data)
    }

    fetchGitHubData();

  }, [])


  return(
    <div>
      <Head>
        <title>Darren Medrano</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" />
      </Head>
          <div className={styles.main}>
          <div className={styles.left}>
            <div class={styles.profileCard}>
              <Avatar size="2xl" src={avatarUrl} />
              <div className={styles.cardText}>
                <h2 className={styles.name}>{username}</h2>
                <p className={styles.bio}>{bio}</p>
              </div>
          </div>
          <div className={styles.bottomLeft}>
                <ContributionCalendar/>
              </div>
              </div>
        <div className={styles.content}>
        <ActiveRepos/>
        </div>
        </div>
    </div>
  );
};
