import Head from "next/head";



export default function Home() {
  return (
    <>
      <Head>
        <title>Darren Medrano</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" />
      </Head>
      <h1>
        Hello
      </h1>
    </>
  );
}